import type { LabelDictionary } from './types';

/**
 * Default Vorrai labels — B2B-SaaS vocabulary used by marketing-vertical
 * tenants (vendia.vip, jhcontext.com, etc.). The clinical dictionary
 * overrides these for tenants with vertical === 'clinical'.
 */
export const DEFAULT_LABELS: LabelDictionary = {
  // Menu groups
  groupHome:       'Home',
  groupContent:    'Content',
  groupManagement: 'Management',
  groupManager:    'Manager',

  // Main nav
  dashboard: 'Dashboard',
  bookings:  'Bookings',
  leads:     'Leads',
  chats:     'Chats',

  // Content nav
  followups:    'Followups',
  templates:    'Templates',
  contents:     'Contents',
  contentJobs:  'Jobs',
  blog:         'Blog',
  subscribers:  'Subscribers',

  // Management nav
  products:        'Products',
  personas:        'Personas',
  offers:          'Offers',
  courses:         'Courses',
  council:         'Council',
  councilHistory:  'Council History',
  optimization:    'Optimization',

  // Pages
  leadsTitle:        'Leads',
  leadsSubtitle:     'Prospects captured from your landing pages and chat sessions',
  leadSingular:      'Lead',
  prospectSingular:  'Prospect',

  chatsTitle:           'Conversations',
  chatsSubtitle:        'Active SPIN Selling chat sessions with your leads',
  receptionistAiName:   'SpinChat AI',

  bookingsTitle:    'Calendar',
  bookingsSubtitle: 'Manage bookings and calendar connections',

  followupsTitle:    'Followups',
  followupsSubtitle: 'Followup Emails generated for the leads that have gone through the SPIN Selling Chat',
  episodeSingular:   'Episode',

  contentsTitle:     'Contents',
  contentsSubtitle:  'Content pieces generated by the AI for your campaigns and channels',

  contentJobsTitle:    'Content Generation Jobs',
  contentJobsSubtitle: 'Background jobs processing your AI content generation requests',

  // Settings
  aiLimitsTitle:      'AI Limits',
  webChatLimitLabel:  'Web Chat Max Characters',
  agentLimitLabel:    'AI Employee / Agent Max Characters',

  // Manager
  managerLeadsColumn: 'Leads',
};
